In [1]:
import numpy as np

In [9]:
valoraciones = np.array([[8,54,84,61,2],[84,61,561,13,1],[48,46,12,3,6]])
valoraciones

array([[  8,  54,  84,  61,   2],
       [ 84,  61, 561,  13,   1],
       [ 48,  46,  12,   3,   6]])

In [11]:
valoraciones[1][2]

561

In [16]:
valoraciones2 = np.array([[[8,54,84,61,2,5],[84,61,561,13,1,45],[48,46,12,3,6,345]],[[8,54,84,61,2,5],[84,61,691,13,1,45],[48,46,12,3,6,345]]])
valoraciones2

array([[[  8,  54,  84,  61,   2,   5],
        [ 84,  61, 561,  13,   1,  45],
        [ 48,  46,  12,   3,   6, 345]],

       [[  8,  54,  84,  61,   2,   5],
        [ 84,  61, 691,  13,   1,  45],
        [ 48,  46,  12,   3,   6, 345]]])

In [17]:
valoraciones2[1,1,2]

691

In [19]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [21]:
valoraciones2 + np.ones((2,3,6))

array([[[  9.,  55.,  85.,  62.,   3.,   6.],
        [ 85.,  62., 562.,  14.,   2.,  46.],
        [ 49.,  47.,  13.,   4.,   7., 346.]],

       [[  9.,  55.,  85.,  62.,   3.,   6.],
        [ 85.,  62., 692.,  14.,   2.,  46.],
        [ 49.,  47.,  13.,   4.,   7., 346.]]])

In [22]:
np.mean(valoraciones2)

83.55555555555556

In [25]:
np.mean(valoraciones2,axis=2)

array([[ 35.66666667, 127.5       ,  76.66666667],
       [ 35.66666667, 149.16666667,  76.66666667]])

In [26]:
np.random.rand(2,5)

array([[0.76245264, 0.10904423, 0.85410832, 0.89607353, 0.79996621],
       [0.47608362, 0.1002912 , 0.05770691, 0.60198396, 0.57605117]])